name: Build and deploy to gh-pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'web/**'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy web/ to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          publish_branch: gh-pages
          commit_message: "Deploy web/ to gh-pages"